### PR TITLE
Backmerge upstream main into `fb-RES-849-reaktoro-v2-long-lived`

### PR DESCRIPTION
**Pull request by hendriko373**
This contains the fixes for the caching issues in the activity model computations.

RFDAP-6795

### CODE REVIEW

**Review by rafaeljalves — APPROVED** [review]
Nice!
This will close [RFDAP-6795](https://esss.atlassian.net/browse/RFDAP-6795), right?

**Comment by hendriko373** [comment]
> Nice! This will close [RFDAP-6795](https://esss.atlassian.net/browse/RFDAP-6795), right?

Not yet, as there are still some changes to be merged in `pore`.

**Review by tadeu — APPROVED** [review]
Great fix, thanks!

**Comment by hendriko373** [comment]
Closing this PR and replacing it with #17 , in order to merge changes simultaneously with downstream changes.

**Pull request closed without merging**
